[package]
name = "edgeware-backward-compatibility-runtime-interface"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware runtime interface helpers and functions"
edition = "2018"

[dependencies]
node-primitives = { version = "2.0.0-rc2", path = "../primitives" }
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-runtime = { version = "2.0.0-rc2", path = "../../../primitives/runtime" }
sp-runtime-interface = { version = "2.0.0-rc2", path = "../../../primitives/runtime-interface" }
# sp-runtime-interface-proc-macro = { git = "https://github.com/hicommonwealth/substrate.git", branch = "time-travel" }

[features]
default = [ "std" ]
std = [
  "sp-runtime/std",
  "sp-runtime-interface/std",
]